<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function findAllCommentsByPostId($postId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle:Comment c where c.post = :postId')
            ->setParameter('postId', $postId)
            ->getResult();
    }
}
